### ISSUE TITLE
Ein Projekt sollte zu mehreren OK Labs gehören können

### ISSUE THREAD

**Issue by gitviola** [okfde/2013.archiv.codefor.de#568]
Derzeit ist die Webseite darauf ausgelegt, dass nur ein Projekt zu einem OK Lab gehören kann.

Mit den Labs Ruhrgebiet, Niederrhein und Düsseldorf wird es in Zukunft wohl öfter Projekte geben, die von mehr als einem OK Lab umgesetzt werden.

Deshalb müsste das irgendwie in die jekyll-Struktur eingebracht werden.

**Derzeit:**

``` yaml

---
layout: project
lab: OK Lab Ruhrgebiet
imgname: ruhrgebiet/schulradar.jpg
title: Schulradar NRW
status: In Progress
```

**Wunschvorstellung:** _(für den Fall, dass mehrere Labs dahinter stecken)_

``` yaml

---
layout: project
lab:
  - OK Lab Ruhrgebiet
  - OK Lab Niederrhein
imgname: ruhrgebiet/schulradar.jpg
title: Schulradar NRW
status: In Progress
```
